name: tutorial
channels:
  - defaults
dependencies:
  - pandas>=1.0.0
  - scikit-learn=0.22.1
  - pip
  - pip:
    - git+https://github.com/saagie/mlflow.git@branch-1.16-saagie
    - pyarrow
    - numpy
